FROM --platform=$BUILDPLATFORM golang:1.24-alpine AS ingress-build

ARG TARGETOS
ARG TARGETARCH
WORKDIR /src/apps/ingress
COPY apps/ingress/go.mod ./
COPY apps/ingress ./
RUN test "$TARGETOS" = "linux"
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -trimpath -ldflags="-s -w" -o /out/cpamp-ingress ./cmd/cpamp-ingress

FROM alpine:3.21
RUN apk add --no-cache ca-certificates tzdata \
    && addgroup -S cpamp \
    && adduser -S -G cpamp -H cpamp
COPY --from=ingress-build /out/cpamp-ingress /usr/local/bin/cpamp-ingress
USER cpamp:cpamp
EXPOSE 18317
ENTRYPOINT ["/usr/local/bin/cpamp-ingress"]
